PROEV-246 ANDROID Создать подсказки по заполнению e-mail при регистрации
ProEvent2021/ProEvent_android pull request #18
Opened 2022-01-28 09:19 UTC by ivanKil

2022-01-28 10:57 UTC, VMoLinov approved these changes

2022-01-30 12:21 UTC, GrishaninVyacheslav requested changes
@ivanKil чтобы слить с master нужно разрешить конфликты. Попробуй сделать rebase своей ветки на последний коммит master-а, вроде должно помочь. Или, если хочешь, я могу через github конфликты разрешить, просто граф git-а получится не красивый

2022-01-31 11:19 UTC, GrishaninVyacheslav approved these changes
Отлично. Единственное у меня не было подсказок для исправления опечаток. Например yadex.ru → yandex.ru как заявлено на сайте API. Это проблема API или со стороны приложения исправления не предлагаются?

2022-01-31 11:19 UTC, GrishaninVyacheslav commented on app/src/main/java/ru/myproevent/domain/models/repositories/proevent_login/IProEventLoginRepository.kt
> +    fun getEmailHint(part_email: String): Single<List<Suggestion>>
Работу с подсказками лучше вынести в отдельную сущность(репозиторий/провайдер)

2022-01-31 11:20 UTC, merged